CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL ,
    age INT NOT NULL,
    address VARCHAR(255),
    startDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE polls (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    answer1 VARCHAR(255) NOT NULL,
    answer2 VARCHAR(255) NOT NULL,
    answer3 VARCHAR(255) NOT NULL,
    answer4 VARCHAR(255) NOT NULL
);

CREATE TABLE answers (
    pollId BIGINT PRIMARY KEY AUTO_INCREMENT,
    userId BIGINT,
    answerIndex INT NOT NULL
);